### ISSUE TITLE
kernel does not show up in UI

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlite/serverlite-cookiecutter-ts#8]
## Description
kernel created with cookiecutter does not appear

## Reproduce

1. follow instructions from readme:
2. jupyter lite build:
```
jupyter lite build          
static:jupyter-lite.json
.  pre_status:static:jupyter-lite.json
    tarball:  jupyterlite-app-0.1.0-alpha.12.tgz 17MB
    output:   /home/derthorsten/src/jupyterlite_xeus_lua/_output
    lite dir: /home/derthorsten/src/jupyterlite_xeus_lua
    apps:     ('lab', 'retro')
archive:archive
contents:contents
lite:jupyter-lite.json
serve:contents
settings:overrides
translation:translation
.  status:archive:archive
[LiteBuildApp] No archive (yet): jupyterlite_xeus_lua-jupyterlite.tgz
.  status:contents:contents
    contents: 0 files
.  status:lite:jupyter-lite.json
[LiteBuildApp]     jupyter-lite.(json|ipynb): 0 files
.  status:serve:contents
    will serve 8000 with: tornado
.  status:settings:overrides
    overrides.json: 0
.  status:translation:translation
    translation files: 2 files
static:output_dir
-- pre_init:static:output_dir
static:unpack
-- init:static:unpack
federated_extensions:copy:ext:jupyterlite-xeus-lua
-- pre_build:federated_extensions:copy:ext:jupyterlite-xeus-lua
translation:copy
.  build:translation:copy
federated_extensions:patch
-- post_build:federated_extensions:patch
```
3. jupyter lite serve:
```
jupyter lite serve
static:jupyter-lite.json
.  pre_status:static:jupyter-lite.json
    tarball:  jupyterlite-app-0.1.0-alpha.12.tgz 17MB
    output:   /home/derthorsten/src/jupyterlite_xeus_lua/_output
    lite dir: /home/derthorsten/src/jupyterlite_xeus_lua
    apps:     ('lab', 'retro')
archive:archive
contents:contents
lite:jupyter-lite.json
serve:contents
settings:overrides
translation:translation
.  status:archive:archive
[LiteServeApp] No archive (yet): jupyterlite_xeus_lua-jupyterlite.tgz
.  status:contents:contents
    contents: 0 files
.  status:lite:jupyter-lite.json
[LiteServeApp]     jupyter-lite.(json|ipynb): 0 files
.  status:serve:contents
    will serve 8000 with: tornado
.  status:settings:overrides
    overrides.json: 0
.  status:translation:translation
    translation files: 2 files
static:output_dir
-- pre_init:static:output_dir
static:unpack
-- init:static:unpack
federated_extensions:copy:ext:jupyterlite-xeus-lua
-- pre_build:federated_extensions:copy:ext:jupyterlite-xeus-lua
translation:copy
.  build:translation:copy
federated_extensions:patch
-- post_build:federated_extensions:patch
serve:tornado
.  serve:serve:tornado
[LiteServeApp] WARNING | 

        Serving JupyterLite from:
            /home/derthorsten/src/jupyterlite_xeus_lua/_output
        on:
            http://127.0.0.1:8000/index.html

        *** Press Ctrl+C to exit **
        
WARNING:tornado.access:404 GET /jupyter-lite.ipynb (127.0.0.1) 1.22ms
WARNING:tornado.access:404 GET /lab/jupyter-lite.ipynb (127.0.0.1) 0.44ms
WARNING:tornado.access:404 GET /jupyter-lite.ipynb (127.0.0.1) 0.28ms
WARNING:tornado.access:404 GET /api/contents/all.json (127.0.0.1) 0.63ms
```

## Expected behavior
kernel visible in UI

## Context

```
jupyter lite --version
0.1.0a12

 jupyterlite_xeus_lua jupyter --version     
Selected Jupyter core packages...
IPython          : 7.28.0
ipykernel        : 6.4.1
ipywidgets       : not installed
jupyter_client   : 7.0.5
jupyter_core     : 4.8.1
jupyter_server   : 1.11.0
jupyterlab       : 3.1.14
nbclient         : 0.5.4
nbconvert        : 6.2.0
nbformat         : 5.1.3
notebook         : 6.4.4
qtconsole        : not installed
traitlets        : 5.1.0
```

- Operating System and version: ubuntu 20.4
- Browser and version: chrome

<details><summary>Browser Output</summary>
<pre>
config-utils.js:193 GET http://127.0.0.1:8000/lab/jupyter-lite.ipynb 404 (Not Found)
getLiteConfig @ config-utils.js:193
getPathConfig @ config-utils.js:159
jupyterConfigData @ config-utils.js:95
main @ config-utils.js:234
(anonymous) @ config-utils.js:252
config-utils.js:200 failed get jupyter-config-data from http://127.0.0.1:8000/lab/jupyter-lite.ipynb
getLiteConfig @ config-utils.js:200
async function (async)
getLiteConfig @ config-utils.js:193
getPathConfig @ config-utils.js:159
jupyterConfigData @ config-utils.js:95
main @ config-utils.js:234
(anonymous) @ config-utils.js:252
config-utils.js:193 GET http://127.0.0.1:8000/jupyter-lite.ipynb 404 (Not Found)
getLiteConfig @ config-utils.js:193
getPathConfig @ config-utils.js:159
jupyterConfigData @ config-utils.js:98
main @ config-utils.js:234
(anonymous) @ config-utils.js:252
config-utils.js:200 failed get jupyter-config-data from http://127.0.0.1:8000/jupyter-lite.ipynb
getLiteConfig @ config-utils.js:200
async function (async)
getLiteConfig @ config-utils.js:193
getPathConfig @ config-utils.js:159
jupyterConfigData @ config-utils.js:98
main @ config-utils.js:234
(anonymous) @ config-utils.js:252
index.js:8 JupyterLite server extension jupyterlite-xeus-lua is activated!
index.js:532 Starting app
validate.js:135 $ref: keywords ignored in schema at path "#/properties/codeCellConfig"
e.exports @ validate.js:135
e.exports @ properties.js:201
e.exports @ validate.js:374
A @ index.js:88
e @ index.js:55
y._compile @ ajv.js:348
y.getSchema @ ajv.js:204
validateData @ settingregistry.js:50
validateData @ settingregistry.js:61
_validate @ settingregistry.js:457
_load @ settingregistry.js:345
(anonymous) @ settingregistry.js:368
async function (async)
(anonymous) @ settingregistry.js:368
_preload @ settingregistry.js:364
f @ settingregistry.js:161
activate @ settingsplugin.js:16
async function (async)
activate @ settingsplugin.js:18
(anonymous) @ index.es6.js:163
Promise.then (async)
e.activatePlugin @ index.es6.js:162
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
(anonymous) @ index.es6.js:282
e.start @ index.es6.js:281
(anonymous) @ index.js:533
async function (async)
(anonymous) @ index.js:44
60880 @ index.js:539
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
async function (async)
(anonymous) @ bootstrap.js:75
37559 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:5
(anonymous) @ bundle.js:1
validate.js:135 $ref: keywords ignored in schema at path "#/properties/markdownCellConfig"
e.exports @ validate.js:135
e.exports @ properties.js:201
e.exports @ validate.js:374
A @ index.js:88
e @ index.js:55
y._compile @ ajv.js:348
y.getSchema @ ajv.js:204
validateData @ settingregistry.js:50
validateData @ settingregistry.js:61
_validate @ settingregistry.js:457
_load @ settingregistry.js:345
(anonymous) @ settingregistry.js:368
async function (async)
(anonymous) @ settingregistry.js:368
_preload @ settingregistry.js:364
f @ settingregistry.js:161
activate @ settingsplugin.js:16
async function (async)
activate @ settingsplugin.js:18
(anonymous) @ index.es6.js:163
Promise.then (async)
e.activatePlugin @ index.es6.js:162
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
(anonymous) @ index.es6.js:282
e.start @ index.es6.js:281
(anonymous) @ index.js:533
async function (async)
(anonymous) @ index.js:44
60880 @ index.js:539
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
async function (async)
(anonymous) @ bootstrap.js:75
37559 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:5
(anonymous) @ bundle.js:1
validate.js:135 $ref: keywords ignored in schema at path "#/properties/rawCellConfig"
e.exports @ validate.js:135
e.exports @ properties.js:201
e.exports @ validate.js:374
A @ index.js:88
e @ index.js:55
y._compile @ ajv.js:348
y.getSchema @ ajv.js:204
validateData @ settingregistry.js:50
validateData @ settingregistry.js:61
_validate @ settingregistry.js:457
_load @ settingregistry.js:345
(anonymous) @ settingregistry.js:368
async function (async)
(anonymous) @ settingregistry.js:368
_preload @ settingregistry.js:364
f @ settingregistry.js:161
activate @ settingsplugin.js:16
async function (async)
activate @ settingsplugin.js:18
(anonymous) @ index.es6.js:163
Promise.then (async)
e.activatePlugin @ index.es6.js:162
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
(anonymous) @ index.es6.js:282
e.start @ index.es6.js:281
(anonymous) @ index.js:533
async function (async)
(anonymous) @ index.js:44
60880 @ index.js:539
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
async function (async)
(anonymous) @ bootstrap.js:75
37559 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:5
(anonymous) @ bundle.js:1
validate.js:135 $ref: keywords ignored in schema at path "#/properties/codeCellConfig"
e.exports @ validate.js:135
e.exports @ properties.js:201
e.exports @ validate.js:374
A @ index.js:88
e @ index.js:55
y._compile @ ajv.js:348
y.getSchema @ ajv.js:204
validateData @ settingregistry.js:51
validateData @ settingregistry.js:61
_validate @ settingregistry.js:457
_load @ settingregistry.js:345
(anonymous) @ settingregistry.js:368
async function (async)
(anonymous) @ settingregistry.js:368
_preload @ settingregistry.js:364
f @ settingregistry.js:161
activate @ settingsplugin.js:16
async function (async)
activate @ settingsplugin.js:18
(anonymous) @ index.es6.js:163
Promise.then (async)
e.activatePlugin @ index.es6.js:162
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
(anonymous) @ index.es6.js:282
e.start @ index.es6.js:281
(anonymous) @ index.js:533
async function (async)
(anonymous) @ index.js:44
60880 @ index.js:539
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
async function (async)
(anonymous) @ bootstrap.js:75
37559 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:5
(anonymous) @ bundle.js:1
validate.js:135 $ref: keywords ignored in schema at path "#/properties/markdownCellConfig"
e.exports @ validate.js:135
e.exports @ properties.js:201
e.exports @ validate.js:374
A @ index.js:88
e @ index.js:55
y._compile @ ajv.js:348
y.getSchema @ ajv.js:204
validateData @ settingregistry.js:51
validateData @ settingregistry.js:61
_validate @ settingregistry.js:457
_load @ settingregistry.js:345
(anonymous) @ settingregistry.js:368
async function (async)
(anonymous) @ settingregistry.js:368
_preload @ settingregistry.js:364
f @ settingregistry.js:161
activate @ settingsplugin.js:16
async function (async)
activate @ settingsplugin.js:18
(anonymous) @ index.es6.js:163
Promise.then (async)
e.activatePlugin @ index.es6.js:162
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
(anonymous) @ index.es6.js:282
e.start @ index.es6.js:281
(anonymous) @ index.js:533
async function (async)
(anonymous) @ index.js:44
60880 @ index.js:539
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
async function (async)
(anonymous) @ bootstrap.js:75
37559 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:5
(anonymous) @ bundle.js:1
validate.js:135 $ref: keywords ignored in schema at path "#/properties/rawCellConfig"
e.exports @ validate.js:135
e.exports @ properties.js:201
e.exports @ validate.js:374
A @ index.js:88
e @ index.js:55
y._compile @ ajv.js:348
y.getSchema @ ajv.js:204
validateData @ settingregistry.js:51
validateData @ settingregistry.js:61
_validate @ settingregistry.js:457
_load @ settingregistry.js:345
(anonymous) @ settingregistry.js:368
async function (async)
(anonymous) @ settingregistry.js:368
_preload @ settingregistry.js:364
f @ settingregistry.js:161
activate @ settingsplugin.js:16
async function (async)
activate @ settingsplugin.js:18
(anonymous) @ index.es6.js:163
Promise.then (async)
e.activatePlugin @ index.es6.js:162
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
(anonymous) @ index.es6.js:282
e.start @ index.es6.js:281
(anonymous) @ index.js:533
async function (async)
(anonymous) @ index.js:44
60880 @ index.js:539
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
async function (async)
(anonymous) @ bootstrap.js:75
37559 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:5
(anonymous) @ bundle.js:1
6[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
index.js:534 JupyterLite started, waiting for restore
index.js:536 JupyterLite restored
contents.js:281 GET http://127.0.0.1:8000/api/contents/all.json 404 (Not Found)
getServerDirectory @ contents.js:281
getFolder @ contents.js:250
async function (async)
getFolder @ contents.js:242
get @ contents.js:183
(anonymous) @ server.js:63
route @ router.js:85
fetch @ server.js:30
e.handleRequest @ serverconnection.js:208
e.makeRequest @ serverconnection.js:77
get @ index.js:507
get @ index.js:200
cd @ model.js:231
factory @ model.js:82
e._execute @ index.es6.js:374
c @ index.es6.js:313
requestAnimationFrame (async)
(anonymous) @ index.es6.js:317
(anonymous) @ index.es6.js:78
(anonymous) @ index.es6.js:59
a @ index.es6.js:49
Promise.then (async)
c @ index.es6.js:51
(anonymous) @ index.es6.js:52
c @ index.es6.js:48
e.schedule @ index.es6.js:277
e.refresh @ index.es6.js:253
refresh @ model.js:197
i @ index.js:902
async function (async)
i @ index.js:883
l @ index.es6.js:459
n.emit @ index.es6.js:416
n.emit @ index.es6.js:99
l @ router.js:122
route @ router.js:140
(anonymous) @ index.js:503
Promise.then (async)
activate @ index.js:501
(anonymous) @ index.es6.js:163
Promise.then (async)
e.activatePlugin @ index.es6.js:162
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveRequiredService @ index.es6.js:206
(anonymous) @ index.es6.js:156
e.activatePlugin @ index.es6.js:156
e.resolveOptionalService @ index.es6.js:239
(anonymous) @ index.es6.js:158
e.activatePlugin @ index.es6.js:158
(anonymous) @ index.es6.js:282
e.start @ index.es6.js:281
(anonymous) @ index.js:533
async function (async)
(anonymous) @ index.js:44
60880 @ index.js:539
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
async function (async)
(anonymous) @ bootstrap.js:75
37559 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:5
(anonymous) @ bundle.js:1
contents.js:288 don't worry, about SyntaxError: Unexpected token T in JSON at position 0... nothing's broken. if there had been a
          file at http://127.0.0.1:8000/api/contents/all.json, you might see some more files.
</pre>
</details>

**Comment by DerThorsten** [comment]
ok, I think this was jusy me beeing stupid....the cookiecutter does not build a kernel but rather an empty extension

**Comment by jtpio** [comment]
Thanks @DerThorsten.

Mind sharing the code of the kernel extension?

This cookiecutter does not add a kernel (yet) but simply log something in the dev tools console.

**Comment by DerThorsten** [comment]
Once I have the code sure =)

**Comment by jtpio** [comment]
> ok, I think this was jusy me beeing stupid....the cookiecutter does not build a kernel but rather an empty extension

Right. We could add that to the cookiecutter (maybe as part of #2).

In the meantime there is also this `echo-kernel` which is mostly meant to be an example: https://github.com/jupyterlite/echo-kernel
